version: '3.5'

services:
  proxy:
    container_name: proxy-nginx
    image: carlonicora/nginx-alpine:1.17
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./hosts:/etc/nginx/conf.d:delegated
      - ./includes:/etc/nginx/includes:delegated
      - ./data/certbot/conf:/etc/letsencrypt:delegated
      - ./data/certbot/www:/var/www/certbot:delegated
    networks:
      - carlonicora
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:delegated
      - ./data/certbot/www:/var/www/certbot:delegated
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  carlonicora:
    driver: bridge
    name: carlonicora
